### PR TITLE
Restructure account names other than assets account.

### PR DESCRIPTION
**Pull request by kaguillera**
Corrections of account structure

### CODE REVIEW

**Comment by chadwhitacre** [comment]
What's going on here is that in #41 we corrected the remaining `Assets` accounts, but we *over*corrected and changed Income/Expense accounts as well.

**Comment by chadwhitacre** [comment]
@kaguillera talked this through IRL.

@kaguillera The merge is yours. :-)

**Comment by chadwhitacre** [comment]
Decided to do basic error correction here but not worry too much about chart of accounts, since we are bumping that to professionals on #43.

**Comment by kaguillera** [comment]
ok Look good to me.  merging

**Pull request merged**
