### PR TITLE
Add balance assertion for 2012-06

### PR DESCRIPTION
**Pull request by nobodxbodon**
To implement https://github.com/gratipay/finances/issues/39#issuecomment-283946489

### CODE REVIEW

**Comment by nobodxbodon** [comment]
@whit537 @kaguillera et al. please review.

**Comment by chadwhitacre** [comment]
This needs a README update, and I also am not sure about daily balance assertions vs. monthly. Where are those daily balance assertions coming from? The bank statement? Can you link me to the logfile where those are coming from?

**Comment by nobodxbodon** [comment]
@whit537 here's the reference where assertions are from: https://github.com/gratipay/logs/blob/master/statements/2012/06/new-alliance.csv
Note that I picked the last one out of the multiple records in each day.

**Comment by chadwhitacre** [comment]
@nobodxbodon Thanks. It think it is sufficient to assert a single balance, at the end of the month, as part of the reconciliation process. I think more than that is more clutter and trouble than it's worth.

**Comment by chadwhitacre** [comment]
Can you live with 220732babaf8ad038244b1d83b3089732beceb13?

I don't like that we have to open the `Assets:New-Alliance` account, because then we can post money against it when we'd really rather not.

**Comment by chadwhitacre** [comment]
But I don't see a way around that. :-/

**Comment by nobodxbodon** [comment]
> Can you live with 220732b?

Fine for now I think. Thanks.

**Pull request merged**
