### PR TITLE
#28 skeleton Django app with balance sheet page

### PR DESCRIPTION
**Pull request by nobodxbodon**
In /demo directory, start server using:

`$ python manage.py runserver`

Then visit: http://127.0.0.1:8000/balance/

This is a demo app as a first step in #28, without any formatting (pure text from ledger command line result is used as html content), like below:

screen shot 2016-12-17 at 11 43 57 pm

### CODE REVIEW

**Comment by nobodxbodon** [comment]
I copied balance-sheet.py and reporting.py from bin/ and make necessary changes.

Also FY2013 directory is copied as workaround to fix path issue.

**Comment by chadwhitacre** [comment]
Woo-hoo! 💃  I'm looking forward to reviewing this. :-)

!m @nobodxbodon

**Comment by chadwhitacre** [comment]
Actually, let's see how https://github.com/gratipay/finances/issues/28#issuecomment-267852926 plays out ...

**Comment by chadwhitacre** [comment]
Closing in favor of #35.

**Pull request closed without merging**
